name: Formatting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shfmt:
    name: shfmt (Bash)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        uses: mfinelli/setup-shfmt@v3
        with:
          shfmt-version: "3.7.0" # Pin a specific version for consistency

      - name: Check Bash Formatting
        # '-d' (diff) prints the differences to the console and exits with
        # an error code if formatting changes are required.
        # '.' scans the current directory recursively.
        run: shfmt -d .
